### ISSUE TITLE
New condition: Event Type

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.civirules#139]
Hi there,
I'm sorry if you'd rather not have me open an issue for this but I thought this might be the right place.

I am struggling wit setting up a new condition: Event Type
Since Event Type does not have it's own table I modeled my new condition after Contribution Status.

I do not get it to work though, I think I am close but I think I am stuck at the Entity it belongs to.
My trigger is "Event Participant Changed", but either 'Event' or 'Participant' do not seem to work in my new file: CRM/CivirulesConditions/Event/Type.php (line 60)

```
public function requiredEntities() {
    return array('Event');
```
When I try to add the condition I get the warning:
`This condition is not available with trigger Event Participant is added`

Any clue on how to proceed?

**Comment by jaapjansma** [comment]
I am not sure why it is not working. I would assume the name of the entity is `Participant`
I have never tested civirules with event registrations so it could be that this is something which is never been developed fully.

**Comment by abbyspenguin** [comment]
I agree - Event Type is a needed condition type in CiviRules. I was hoping to use this to send out an informational email depending on the event type, but event type isn't an option. And I'm not sure how to create this condition myself.

**Comment by ErikHommel** [comment]
@abbyspenguin is that because you are not a developer or because you do not know how to add a condition? If it is the latter, check https://docs.civicrm.org/civirules/en/latest/create-your-own-introduction/
If you are not a developer, is the issue pressing enough for you to fund it?

**Comment by abbyspenguin** [comment]
I'm a developer, but haven't worked with this part. So I'm not entirely certain where to start. I had already looked at that page, but still wasn't sure where to start. Funding it really depends on how much it is, as it would have to come out of my own pay (not an organization funding it). It's really frustrating that there is no way to send an automated email after someone registers except for the receipt or based on the event's start/end date. I guess folks miss that being able to send out an email with information about the event, information to prepare you for it (like for a conference or training), etc is an important task. It's hard to believe it's missing.

**Comment by ErikHommel** [comment]
I get that it is frustrating. It is missing because we never aimed to develop a full blown product that would do what is required. We aimed to develop the extension with the conditions our customers required AND an engine that allowed others to create their own conditions. 

There will be lots of conditions where people who work with them every day do not understand they are not there. At the moment none of our direct customers use CiviRules with Event Registration. It is quite possible that someone else does and has created that condition, but in that case they have not shared it unfortunately.

We do try to do a sprint once a year for CiviRules issues, but unless we win the lottery we can not afford to do all issues without funding. We hope you understand that :-)
I reckon adding the event type condition would take 2-4 hours.
If you do want to give it a try, you will have to develop a CiviCRM extension (I assume you know how to) and then add the classes as explained in the documentation. There are quite a few examples in the CiviRules code to work from.

**Comment by jaapjansma** [comment]
You can fork this repo and then add the event type to the civirules and send a Pull Request back. 
You could have a look at Contribution is of Financial type condition on how to implement this condition. 
And the docs on how to create your own condition are at: https://docs.civicrm.org/civirules/en/latest/create-your-own-condition/

**Comment by jaapjansma** [comment]
Working on create condition for event type, participant has role, participant has status.

**Comment by jaapjansma** [comment]
Added a condition for:
* Event type
* Participant has role
* Participant has status
