### ISSUE TITLE
Action should use new data after delay if rechecking is enabled

### ISSUE THREAD

**Issue by adanielvv** [CiviCooP/org.civicoop.civirules#202]
**Example** (only one I could think of right now)
_Example rule_
Trigger: Activity is added
Action: Add tag to contact
Delay by 1 minutes
Unchecked: Don't recheck condition upon processing of delayed action

_Replicate issue_
1. Create the above example rule
2. Add activity, and assign to contact.
3. Change activity and assign to other contact (or delete: see #200).
4. After a minute: run the job Process delayed civirule actions

_Result_
Tag is added to first assigned contact.

_Expected result IMHO_
If rechecking is enabled (this case):
Tag is added to last assigned contact.

If rechecking is disabled:
Tag is added to first assigned contact.

**Comment by ErikHommel** [comment]
Related to #200 

We discussed this and decided we will not fix this issue. The concept is that some data is stored in the queue record. We do not feel we can change this concept of the engine to one that always refreshes the data without running into the same kind of problems (but now from the "other sidee" ) with that approach.

If the fact that some of the trigger data is out of date causes a problem it can easily be fixed by creating a specific condition or action.

We have used CiviRules now with several projects and have ourselves never run into a situation where this was a problem and would be really hesitant to change the engine.
