### ISSUE TITLE
Notices when disabling CiviRules?

### ISSUE THREAD

**Issue by khorporative** [CiviCooP/org.civicoop.civirules#220]
Hello!

If I deleted all rules, disabled CiviRules (see screenshot) and uninstalled the extension, is it a clean removal? Do these notification influence something about the system? If I reinstall the CiviRules, will it be a clean install?

![image](https://user-images.githubusercontent.com/18428628/40782158-28c862b2-64e7-11e8-951b-57f374ee6272.png)

**Comment by jaapjansma** [comment]
Yes uninstalling civirules should remove everything.

**Comment by kainuk** [comment]
These notices are an effect of the rules that are added as managed entities. So I expect they will disappear when #189 is fixed.

**Comment by ErikHommel** [comment]
@khorporative the fix for #189 will make sure this does not happen again. If you have already installed CiviRules and want to get rid of the managed entities causing these notices you can do:
``SELECT * FROM civicrm_managed WHERE module = 'org.civicoop.civirules' AND entity_type IN ('CiviRuleCondition', 'CiviRuleAction', 'CiviRuleTrigger')
