### ISSUE TITLE
Need to add 'last xxx years' and 'last xxx months' to period selection

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#26]
The periods in CiviRules at the moment contain:
* this month
* previous month
* last 30 days
* last 12 months
* last 13 months
* this year
* previous year

For MAF we need at least 'last 3 years' added, but I could imagine it would be better to add:
* last xxx months
* last xxx years
and perhaps even
* last xxx dyas
* last xxx weeks

**Comment by PalanteJon** [comment]
Erik - I've done a lot of work on the core Civi relative date filters for 4.7 (CRM-16195).  There's a wiki page here: http://wiki.civicrm.org/confluence/display/CRM/Notepad+for+CRM-16195.  While the work isn't complete, it might be worth discussing if you could make use of some of the code changes I'm making and leverage the BAO functions to make your work here easier.  Let me know if you want to chat about it.

**Comment by ErikHommel** [comment]
Thanks @PalanteJon, cool! We will certainly have a look!

**Comment by jaapjansma** [comment]
@PalanteJon thanks for sharing! I think you are doing a good job with reletave dates. However as I understand you are still developing this and it should be shipped with 4.7? However I do think that it is too early for us to start using this because the only site where this extension is used in production is on a Civi 4.4 site. So I would rather go for broad version compatibility rather than the latest and gratest.
