### ISSUE TITLE
Branches?

### ISSUE THREAD

**Issue by JoeMurray** [CiviCooP/org.civicoop.civirules#41]
Some of our extensions support multiple versions of CiviCRM, others have different releases for different versions of CiviCRM. Are you thinking that modifications to support 4.6 should also work with 4.4 (the former) or should they be committed to a different branch? 

My guess is that 4.6 will become the LTS release in late 2015, or maybe early 2016.

**Comment by jaapjansma** [comment]
My first thought is that we have one branch which works for all CiviCRM versions.  But let me give you some background on Civirules, the history of Civirules started with MAF Norway they wanted to automate their donor journeys. Other CiviCRM folks showed some interest in this area so we had a brainstorm with them. We then started to develop a specific module for MAF Norway and that was not quite wat was required but it is was for both of us a learning process. So we decided to start over again but try to get others involved as well. So Amnesty Flanders showed up. We then did a combined development so that it will suit MAF Norway and Amnesty Flanders. Both of them are Civi 4.4 so that is the reason Civirules is compatible with Civi 4.4 and tested with Civi 4.4.
However other folks from the community have installed Civirules in Civi 4.6 and have paid to make it compatible for 4.6. The change required for 4.6 where minor ones and did not really needed a seperate branch. (Why would one do that if one could keep one branch). 
My philosophy is to keep things simple and keep them in one place. So in one branch. Unless it causes too much trouble. 

Also keep in mind that our philosophy is that we are not a supplier of software so we wont commit ourselves to keep civirules maintained. However that doesn't mean it wont happen. It could be that we end up with enough clients who think it is worth to maintain the software. But then it is for the sake of the end users and that is a valid reason, I think.

Everybody is free to use, extend etc. So feel free to join the development of Civirules.

**Comment by JoeMurray** [comment]
If people are successfully using it on 4.6 then it seems worthwile to indicate that in info.xml. 

Yes, when it is simple enough to handle multiple CiviCRM versions with one version of slightly more complex code that is simpler overall and preferable, Thanks.
