### ISSUE TITLE
Cannot edit discount codes in Cividiscount when CiviRules enabled

### ISSUE THREAD

**Issue by mattwire** [CiviCooP/org.civicoop.civirules#49]
When I try and edit a discount code (eg. change description, quantity, date etc.) and click Save the page just hangs and never completes.  A page refresh shows that the change has not been applied.

I'm using CiviCRM 4.6.10 and latest versions of CiviRules and CiviDiscount from github as of today:
CiviRules: https://github.com/CiviCooP/org.civicoop.civirules/tree/dba194992950371fc63b2d349cbd648cb94a4e94
CiviDiscount: https://github.com/dlobo/org.civicrm.module.cividiscount/commit/dc2b1cb7b1e6eee6b22758971539065f8a980793

I can give admin access to a test site if required to demo the issue.

**Comment by ErikHommel** [comment]
Hi Matt,
thanks for taking the time to report this, we really appreciate it!

As you might be aware we are sharing CiviRules as a community project, where everyone is free to use, modify and maintain CiviRules. It is not 'our' product nor do we have a standard budget to fix bugs. As it is not our product we also do not guarantee that there will be no bugs on any part of CiviCRM or any extension you combine it with.

I gather from your remark that you expect us to want to have a look at the issue, does that mean you have budget for us to investigate this? Or are you looking for some pointers to be able to deal with the issue yourself? Or are you just making the community aware that the issue is there?

**Comment by mattwire** [comment]
@ErikHommel Hi, no budget :-(  I have not had time to look any further yet, but will do when I get some time.  If you are able to offer any pointers that would be very helpful, in the meantime if anyone else has the problem they can find this issue on github.
Presumably cividiscount is triggering a hook in civirules on submission of the form, so if you have any pointers to where I should start looking for those hooks that would be appreciated.

Regards,
Matthew

**Comment by jaapjansma** [comment]
My first thought is that CiviDiscount triggers a post and/or a pre hook. And that CiviDiscount does not have an entity api

**Comment by ErikHommel** [comment]
I think so too @jaapjansma 

@mattwire there is developer documentation here: http://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+-+how+to+make+your+own
And have a look at issue #47, that was a problem dealing with a similiar type of problem?
And great if you are willing to take a look!!!!

**Comment by ErikHommel** [comment]
No report back on progress, issue closed
