### ISSUE TITLE
CiviCRM 4.7.7 Does not seem to trigger on New Contact

### ISSUE THREAD

**Issue by gah242s** [CiviCooP/org.civicoop.civirules#79]
After adding a new rule to trigger on a new contact being added, nothing happens.  Actions were that the new contact should have been added to a group and an e-mail sent to a separate contact.  Both actions work with other triggers.  There is no log entry or debugging when the trigger is missed.

**Comment by jaapjansma** [comment]
Why is this issue replaced by #90 @gah242s? I don't see why your issue is the same.

**Comment by gah242s** [comment]
It may not be, but it feels like the same behavior, in the same area, and the other report is much broader and spells out the issue much better than I have.  In reading #90 I felt like I was reading what I should have been reporting.  However, you have been much deeper into the code than I could ever hope to be at this point.  (Not for a lack of desire mind you, but of experience and time.)   If they seem to be separate, feel free to clean up the mess I made.

**Comment by jaapjansma** [comment]
Thanks. What probably would work is that you keep an eye on #90 as soon as that one is fixed you can retest if this issue still occurs if not they where releated.

**Comment by PalanteJon** [comment]
I was just playing around with CiviRules, encountered this, and can confirm that it's different from #90.

The issue is with `CRM_Civirules_BAO_Rule::findRulesByObjectNameAndOp()`.  In `civirule_trigger`, the `object_name` is set to "Contact".  However, `hook_civicrm_post` passes the `$objectName` as "Individual".

I have a PR that fixes this that's a little on the hack-ish side, but should be adequate to make the problem clear.
