### ISSUE TITLE
New user Activities created with Actions and delayed do not appear until the scheduled, delayed date?

### ISSUE THREAD

**Issue by joemcl** [CiviCooP/org.civicoop.civirules#95]
For Actions to create new Activities - I want to schedule the Activity with a due date of *later* than the date/time it is triggered, *and* have it appear in the assigned user's Activities list as Scheduled in the future. 

There *is* a setting to have the activity not be scheduled for whatever period of time - to delay it to a day later, three days later, day of the week, etc - but, presumably, the Activity will not actually appear in the user's Activities list until that delayed date - and then it will, of necessity, show as Scheduled, and in red, as past due. 

IMHO it's more useful to have a list of upcoming scheduled Activities.

**Comment by ErikHommel** [comment]
@joemcl I understand but you are taking a limited view of delays IMHO :-) What you would want you should be able to achieve with the scheduled date for the activity created. The delay in the action is created for user stories like: as a fundraiser I want to send an automatic second ask email 4 weeks after receiving the first contribution so I do not have to manage this manually.

So rather than changing the delay what you are saying is that you should be able to set the activity date time in the action, correct?

**Comment by joemcl** [comment]
Erik, thanks but what I mean and want is: based on the delay settings for the Activity scheduled by the Action, add that Activity to the designated user's Activities list as Scheduled to include the delay. So, for example, based on a Linked Trigger of Membership is changed and the Condition is Memberships status is expired, the Action taken is to create three Scheduled Activities: Activity 1, Expired Membership - Send a Postcard, with a 1 day delay; Activity 2, Expired Membership - Send an Email (manually, not automated), with a 2 day delay; Activity 3, Expired Membership - Phone Call, with a 3 day delay. Each of the Activities is created in the user's Activities list immediately with Scheduled dates of 1, 2 and 3 days from now.  

So the CiviRule for this Expired Membership renewal workflow always creates the same Activities with the Scheduled Date for the Activity based on the delay chosen, and the user does not have to adjust the Scheduled date and time for each Activity manually in the user's Activities list.

**Comment by ErikHommel** [comment]
I see Joe :-) That is not what we expected to create with delays, and I think this would only apply to activities in this way. So I still think you should be able to set the activity date in the action rather than using the delay. The delay is meant as a delay for the action, while you want the action to be executed immediately but the dates of the activities to be parameterized, correct?

So I would suggest you add a parameter to the action 'add activity to contact' for activity date time. If you have that you can add each activity as an action to the same rule, with different scheduled dates. Does that make sense? Would you be able to do that or would you prefer us to add the parameter to the action? If so, mail me or @jaapjansma.

**Comment by jaapjansma** [comment]
@joemcl At MAF we have worked today to get the action add activity to include the activity date time which could then be set based on the same options as to delay an action.

**Comment by jaapjansma** [comment]
For anyone interested I wrote a blog on how I accomplished this. See http://bit.ly/2c4d0mp

**Comment by joemcl** [comment]
@jaapjansma great thanks so much will check it out tonight, my time
